# Generated by Django 2.1.2 on 2018-10-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('event_name', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.CharField(max_length=750)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
